# Generated by Django 2.2.4 on 2019-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
